name: testing the code
on:
  push
jobs: 
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: hello bittu
        run: echo "hello bittu"

      - name: displaying the date 
        run: date 
